public enum City {
           MAYKOP ("Майкоп"),
           GORNOALTAYSK ("Горно-Алтайск"),
           UFA ("Уфа"),
           ULANUDE ("Улан-Удэ"),
           MAHACHKALA ("Махачкала"),
           MAGAS ("Магас"),
           NALCHIK ("Нальчик"),
           ELESTA ("Элиста"),
           CHERKESSK ("Черкесск"),
           PETROZAVODSK ("Петрозаводск"),
           CYKTYVKAR ("Сыктывкар"),
           CEMPHEROPOL ("Симферополь"),
           YOSHKORLA ("Йошкар-Ола"),
           SARANSK ("Саранск"),
           YAKUTSK ("Якутск"),
           VLADIKAVKAZ ("Владикавказ"),
           KAZAN ("Казань"),
           KYZYL ("Кызыл"),
           IZCHEVSK ("Ижевск"),
           ABAKAN ("Абакан"),
           GROZNEY ("Грозный"),
           CHEBOKSARY ("Чебоксары"),
           BARNAUL ("Барнаул"),
           CHYTA ("Чита"),
           PETROZAVODSKKAMCHATSKY ("Петропавловск-Камчатский"),
           KRASNODAR ("Краснодар"),
           KRASNOYARSK ("Красноярск"),
           PERM ("Пермь"),
           VLADIVOSTOK ("Владивосток"),
           STAVROPOL ("Ставрополь"),
           HABAROVSK ("Хабаровск"),
           BLAGOVESHENSK ("Благовещенск"),
           ARHANGELSK ("Архангельск"),
           ASTRAHAN ("Астрахань"),
           BELGOROD ("Белгород"),
           BRYANSK ("Брянск"),
           VLADIMIR ("Владимир"),
           VOLGOGRAD ("Волгоград"),
           VOLOGDA ("Вологда"),
           VORONEZH ("Воронеж"),
           IVANOVO ("Иваново"),
           IRKUTSK ("Иркутск"),
           KALININGRAD ("Калининград"),
           KALUGA ("Калуга"),
           KEMEROVO ("Кемерово"),
           KIROV ("Киров"),
           KOSTROMA ("Кострома"),
           KURGAN ("Курган"),
           KURSK ("Курск"),
           SPB ("Санкт-Петербург"),
           LIPECK ("Липецк"),
           MAGADAN ("Магадан"),
           MOSKVA ("Москва"),
           MURMANSK ("Мурманск"),
           NIZHNYNOVGOROD ("Нижний Новгород"),
           VELIKYNOVGOROD ("Великий Новгород"),
           NOVOSIBIRSK ("Новосибирск"),
           OMSK ("Омск"),
           ORENBURG ("Оренбург"),
           OREL ("Орёл"),
           PENZA ("Пенза"),
           PSKOV ("Псков"),
           ROSTOV ("Ростов-на-Дону"),
           RIZAN ("Рязань"),
           SAMARA ("Самара"),
           SARATOV ("Саратов"),
           CAHALINSK ("Южно-Сахалинск"),
           EKATERINBURG ("Екатеринбург"),
           SMOLENSK ("Смоленск"),
           TAMBOV ("Тамбов"),
           TVER ("Тверь"),
           TOMSK ("Томск"),
           TULA ("Тула"),
           TUMEN ("Тюмень"),
           ULYZNOVSK ("Ульяновск"),
           CHELABINSK ("Челябинск"),
           YAROSLAVL ("Ярославль"),
           SEVASTOPOL ("Севастополь"),
           BIROBIDJAN ("Биробиджан"),
           NARYANMAR ("Нарьян-Мар"),
           HANTYMANSYSK ("Ханты-Мансийск"),
           ANADYR ("Анадырь"),
           SALEHARD ("Салехард");

    private String cityName;

    City(String cityName) {
        this.cityName = cityName;
    }

    public String getCityName() {
        return cityName;
    }

    public static City getRandom() {
        return values()[(int) (Math.random() * values().length)];
    }
}
